### ISSUE TITLE
Add Google Cloud Platform resources

### ISSUE THREAD

**Issue by antzi** [xird/geany-hcl-syntax-highlighting#1]
Hi,

As I use Geany to write HCL for GCP, I have added the "google" provider resources and data sources into the filetypes.HCL.conf file. Please review my changes and merge into your repo if you like them.

BR, Anastas

[filetypes.HCL.conf.zip](https://github.com/xird/geany-hcl-syntax-highlighting/files/7287706/filetypes.HCL.conf.zip)

**Comment by xird** [comment]
Added. Thanks!
